### ISSUE TITLE
Gantry on WordPress 3.5.2

### ISSUE THREAD

**Issue by Head-Honco** [gantry/docs-old#70]
New to the framework.
Gantry Theme Framework does not work on Wordpress 3.5.2.
Issue:
Gantry theme Settings are not functional.
Only Widgets & New Over ride have partial functionality [Widgets takes you to the Widgets page & New Override creates a New Setting only-functionality remains dormant]
None of the Save, Presets or Clear Cache events are triggered.

**Comment by newkind** [comment]
I just checked my WP 3.5.2 installations with Gantry and everything works fine, so maybe something went bad durning your update ? Corrupted data ? Plugin conflict ?
Also I don't think that the Documentation github is a good place to report such issues, you should post them in the Gantry WP group at https://groups.google.com/forum/#!forum/gantry-framework-for-wordpress-users

**Comment by Head-Honco** [comment]
Thanks for the heads-up newkind.
