### ISSUE TITLE
Selectbox mobile menu option is not working

### ISSUE THREAD

**Issue by Mohika** [gantry/docs-old#77]
Hi there,
Great work, only I really don't like the new side menu in mobile view, I tried to change panel to select box but its not working, also I see in the news that backward compatibility support is available but I can't see any option I can choose to get old panel menu there.

**Comment by w00fz** [comment]
The select box should be working again. 

Regarding your other question, the backward compatibility is there only in case you were running an old version of RokNavMenu, where the sidepanel is not supported. 
We don't have an option to switch to the vertical panel, this was a decision made based on the "trend" of showing menus on the side of your mobile, which makes sense for us. It's less obtrusive and doesn't force the page height to get higher than already is.

If you want to force the old behavior, a trick would be to delete the file `modules/mod_roknavmenu/themes/default/js/sidemenu.js`.
