### ISSUE TITLE
Category View can't go to the next page.

### ISSUE THREAD

**Issue by magicento** [gantry/docs-old#78]
1.I create two blogs category named "case1" and "case2",and post 6 articles to each category.
2.put those two categories go the menu items.
3.then create two templates overview named "case1overview" and "case1overview",then assign the case1 menu to case1overview,assign the case2 to case2overview.
4.go to the frontpage,when i open the case1 category page,the first page is ok,but when i click the pagination next,the page will result "Sorry, but there aren't any posts matching your query." and i set per an article.
5.when i assgin the " Category Archive Page" to the case1overview or case2overview,when i click the next page ,it will be ok,but all the categories are the same layout,if i want those two categories have  different layout ,how to do?

**Comment by magicento** [comment]
This is a video:
http://pan.baidu.com/share/link?shareid=2142903815&uk=4028631961

**Comment by w00fz** [comment]
Sorry I'm not exactly sure I'm following. Also the video you posted seems is expired. Do you mind elaborating what the issue is and eventually add back the video?
Also is this working with templates that are not Gantry based?

Cheers

**Comment by RyanMPierson** [comment]
Closing due to time without response.
