### ISSUE TITLE
Menu link Title attribute

### ISSUE THREAD

**Issue by adnorek** [gantry/docs-old#82]
Hi, I am unable to find a way to show the "link title attribute" in the menu section on my
template using Gantry. i think it is important for seo. :-(

**Comment by RyanMPierson** [comment]
This particular feature isn't handled by Gantry, but rather is a function of Joomla. You can typically access this by going to the Edit Menu Item page within the Menu Manager. 

If this is set, and not appearing in the output, try disabling RokNavMenu and seeing if that resolves the issue. If so, let us know so we can look into this issue further. Information about your specific configuration (template and Joomla version, in addition to any third-party extensions) could also prove helpful.

Best of luck to you, and thank you for contacting us.

**Comment by Bodge-IT** [comment]
I'm also having the same issue on Panacea template on Joomla2.5.
The panacea html override for mod_roknavmenu does not call the Link Title AtTribute as far as I can see.  getLinkAttribs() is empty as is getLinkAdditionsArray()

**Comment by RyanMPierson** [comment]
We are not able to replicate the issue on J2.5 or J3.x with RokNavMenu. Can you post this issue to our support forums so our team can have a closer look at what's going on? This isn't the best platform for support since it's really only monitored by folks working on the documentation.
