### ISSUE TITLE
-custom.less

### ISSUE THREAD

**Issue by ibanez0r** [gantry/docs-old#86]
-custom.less inclusion not working in Joomla 3.3.0

**Comment by RyanMPierson** [comment]
Hello there,

We recommend posting any issues you're having through our support forums as our Github docs is watched by a different part of our team that might not be able to provide the best answers for you.

We did look in to this report and aren't having issues with custom.less and Joomla 3.3.0. If you've cleared your Joomla cache and are still experiencing an issue, please report via our forums at http://www.rockettheme.com/forum/, thanks!

**Comment by ibanez0r** [comment]
rgr, will do, i think its a localized issue as ive had some friends also check their installs and have reported no issues, ill fire up xdebug and use the forum, thank-you.
