### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ramblerswebs** [gantry/docs-old#93]
Just to say that this pages does not display correctly
http://www.gantry-framework.org/documentation/joomla/configure/layouts.md

**Comment by RyanMPierson** [comment]
Hello there. Thanks for submitting the issue. It's displaying properly on our end. Is there any more information you can give us? What OS, browser version, etc.? Thanks again.

**Comment by ramblerswebs** [comment]
Thanks for such a quick reply
Here is a screen shot of what it looks like on my browser, Firefox 32.0.3, Markdown Viewer 1.6 ext, Windows 7 Pro fully up to date
https://www.dropbox.com/s/mryeec3x79dc75q/Screenshot%202014-10-16%2016.12.55.png?dl=0
