### ISSUE TITLE
Getting some kind of code block on top.

### ISSUE THREAD

**Issue by adarshkhatri** [gantry/docs-old#95]
Hi

Not sure what causing this.
Could you please pin point me.

http://carsonscreens.com.au/

Kind Regards
Adarsh

**Comment by rhukster** [comment]
Please post this kind of question on either the RocketTheme Gantry forums:

http://www.rockettheme.com/forum/gantry-framework

or the mailing list:

https://groups.google.com/forum/#!forum/gantry-framework-for-joomla-users
